### ISSUE TITLE
doom-emacs: does not display cursor and cursor background

### ISSUE THREAD

**Issue by GTrunSec** [honmaple/emacs-maple-explorer#1]
I think this problem unrelated with theme.
I do not have any issue under imenu-list.

![Screenshot_20191110_123808-maple-imenu-issue](https://user-images.githubusercontent.com/21156405/68550423-9b711780-03b7-11ea-8d4b-7bdecfec6285.png)

**Comment by honmaple** [comment]
There are two parameters have been set
```
(setq cursor-type nil
      cursor-in-non-selected-windows nil)
``` 
change them by 
```
(add-hook 'maple-explorer-imenu-mode
          (lambda() (setq cursor-type t
                          cursor-in-non-selected-windows t))
```

**Comment by GTrunSec** [comment]
`(add-hook 'maple-explorer-imenu-mode-hook
          (lambda() (setq cursor-type t
                          cursor-in-non-selected-windows t)))`

it's working !. one more question. how to set background color to cursor which selected on maple imenu
